version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    ports:
      - 3000:3000
    networks:
      - redis-subnet
      - mongo-subnet

networks:
  redis-subnet:
    name: demo-simple-voting-system-graphql_redis-subnet
    external: true
  mongo-subnet:
    name: demo-simple-voting-system-graphql_mongo-subnet
    external: true
