version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-subnet

networks:
  redis-subnet:
    driver: bridge
